Added ten nouns with three actions each
rallevondalle/PFMCPP_Project1 pull request #1
Opened 2021-11-26 23:13 UTC by rallevondalle

2021-11-26 23:34 UTC, matkatmusic requested changes

2021-11-26 23:34 UTC, matkatmusic commented on main.cpp
> +lavalamp.music();
the action is `plays`
the pseudo code needs to say this.
`music` is not an action, it is a noun.
- [ ] revise

2021-11-26 23:34 UTC, matkatmusic commented on main.cpp
> +bicycle.bells();
the action is `dings`
the pseudo code needs to say this.
`bells` is not an action, it is a noun.
- [ ] revise

2021-11-26 23:34 UTC, matkatmusic commented on main.cpp
> +bicycle.ride();
What is the bicycle riding?
Someone else rides the bicycle. 
how about `rolls`.?
"The bicycle rolls forward"
`bicycle.rollForward();`
- [ ] revise

2021-11-26 23:34 UTC, matkatmusic commented on main.cpp
> +plants.photosynthesis();
`plants.photosynthesize();`
'synthesize' is the action.  'synthesis' is the noun.
your pseudocode needs to describe an action.
- [ ] revise

2021-11-27 11:11 UTC, rallevondalle reviewed
Corrected the erroes.

2021-11-27 12:16 UTC, rallevondalle commented
Changed some of the actions, wasn't the most creative ones I came up with last night haha :)

2021-11-28 11:39 UTC, matkatmusic approved these changes

2021-11-28 11:39 UTC, merged